version: "3"
services:
  answer:
    image: oyjx0525/answer
    ports:
      - '9080:80'
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - answer-data:/data
    networks:
      answer-network:
        ipv4_address: 172.33.0.4
  db:
    image: mariadb:10.4.7
    ports:
      - '3306:3306'
    restart: on-failure
    environment:
      MYSQL_DATABASE: answer
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      timeout: 20s
      retries: 10
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake']
    volumes:
      - ./answer-data/mysql:/var/lib/mysql
    networks:
      answer-network:
        ipv4_address: 172.33.0.3
networks:
  answer-network:
    driver: bridge
    name: answer-network
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16
          gateway: 172.33.0.1
