version: "3.1"
services:
  answer:
    image: github.com/segmentfault/answer
    ports:
      - '9080:80'
    restart: on-failure
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '13306:3306'
    restart: on-failure
    environment:
      MYSQL_DATABASE: answer
      MYSQL_ROOT_PASSWORD: root
