version: "3.1"
services:
  answer:
    image: github.com/segmentfault/answer
    ports:
      - '9080:80'
    restart: on-failure
    volumes:
      - data:/data
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - '13306:3306'
    restart: on-failure
    environment:
      MYSQL_DATABASE: answer
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  data:
  db:
